insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Bakker', '0000000001', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Slager', '0000000002', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Bloemist', '0000000003', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Beenhouwer', '0000000004', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Loodgieter', '0000000005', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Schilder', '0000000006', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Bouwvakker', '0000000007', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Traiteur', '0000000008', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Drukkerij', '0000000009', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Kruidenier', '0000000010', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Garagist', '0000000011', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Postbode', '0000000012', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Entertainer', '0000000013', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Kuisvrouw', '0000000014', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Fotograaf', '0000000015', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Leerkracht', '0000000016', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Boekhouder', '0000000017', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('ITer', '0000000018', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Bankbediende', '0000000019', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Architect', '0000000020', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Schrijnwerker', '0000000021', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Daklegger', '0000000022', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Consultent', '0000000023', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Ingenieur', '0000000024', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');
insert into public.account (name, identifier, street_and_number, postal_code, city, country, contact_email, contact_firstname, contact_lastname, contact_language, invoicing_email) values ('Huisvrouw', '0000000025', 'Schuttersvest 75', 2800, 'Mechelen', 'BEL', 'test-contact@ixor.be', 'Voornaam', 'Achternaam', 'nl', 'test-invoicing@ixor.be');


